# Generated by Django 3.1.5 on 2021-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('company', models.CharField(max_length=70)),
                ('salary', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('detail', models.TextField()),
            ],
        ),
    ]
